### ISSUE TITLE
Permission To Use It On A Blog? 

### ISSUE THREAD

**Issue by Phone-Metal** [moPsych/ferris-wheel#1]
Hi, I Really Loved This Would It Be Cool If I Put It On My Blog? =3
i'll give credit to u

**Comment by moPsych** [comment]
Thank you so much. I really appreciate it. Sure you are free to use it everywhere you want. I also have it on OpenProcessing: <a href="https://www.openprocessing.org/sketch/1034456">Ferris Wheel</a> if this would help. Thank you again and good luck.
